<!DOCTYPE html>

<html lang="pt-br"> 
	 
<head>

	<meta charset="UTF-8">
	<link rel="shortcut icon" type="image/x-icon" href="app/views/lightphant-mvc-favicon.ico" />
	<link rel="icon" type="image/x-png" href="app/views/lightphant-mvc-favicon.png" />			 
	
	<!-- Incluir conteúdo da tag header -->	
	<?php require_once( 'app/views/lightphant-head.phtml' ); ?>
	
</head>	 

<body>
	  
	<script>
		//Variáveis globais para serem usadas por qualquer arquivo "*.js"
		var MVC = <?= json_encode(get_defined_constants(true)['user']) ?? '{}' ?>;
	</script> 
	
	<!-- Menu principal -->	
	<?php //require_once( 'app/views/lightphant-menu-principal.phtml' ); ?>
	
	<section id="loading">
		<div>
			<img src='app/views/img/loading-asa-sul.gif' />
		</div>
	</section>
	 
	<section id="cont">
		<div class="compensacao-menu-principal-flutuante"></div> 
		<?php require_once( "app/views/{$pagina}.phtml" ); ?>
	</section>	
	
	<section id="forms">
		<?php //require_once( 'app/views/lightphant-login.phtml' ); ?>
	</section>
	
	<section id="alerts">
		<?php //require_once( 'app/views/lightphant-alertas.phtml' ); ?>
	</section>

</body>

</html>