	

<meta name="author" content="Gleyson Barroso">
<meta name="description" content="Lightphant MVC">

<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>normalize-3.0.1.css"/>
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS; ?>css/lightphant-index.css" media="screen"/>
<!-- plugins da versão full
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>light-frontend-0.6/light-frontend.css" media="screen"/>
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>light-frontend-0.6/light-frontend-mobile.css" media="(max-device-width: 640px)"/>
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>light-table.1.2.0.css" /> 
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>androtab.0.2.css" media="screen"/> 
<link rel="stylesheet" type="text/css" href="<?= URL_BASE . VIEWS_PLUGINS; ?>androtab.mobile.0.2.css" media="(max-device-width: 640px)"/> 

<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>jquery-2.1.3.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>light-frontend-0.6/light-frontend.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>light-table.1.2.0.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>jquery-hotfix-label.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>jqLightForm.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>jqFormValidate.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS_PLUGINS; ?>taphold.js"></script>
<script type="text/javascript" src="<?= URL_BASE . VIEWS; ?>js/phpjs.js"></script>
-->
