
<script type="text/javascript" src="<?= URL_BASE.VIEWS; ?>js/sld-crud.js"></script>


<!-- alertas de crud ---------------------------------------------------------->
<form 
    id="confirmar-exclusao"
    class="crud-alertas lf-modal lf-tema-light"
    action=""
    >
    <div class="lf-modal-janela -normal" style="width: 450px;">

        <div class="lf-modal-janela-topo -black">
            <b><i class="fa fa-trash"></i> Confirmar Exclusão</b>
            <a class="lf-botao -black" href=""><i class="fa fa-times"></i></a>
        </div>	

        <div class="lf-modal-alerta-conteudo" style="font-size: 1.2em;">

            <p>
                Você tem certeza que deseja excluir este(s) registros(s)?
            </p>

            <div class="lf-form" style="margin-top: 0.7em;">

                <div class="lf-form-coluna-label-invertido">
                    <label>Id(s):</label>
                    <input name="dis-id" disabled value="">
                </div>
                
                <div class="inputs-ocultos-para-exclusao lf-none">
                    <!-- preenchido via sld-crud.js com inputs[] a serem desativados. -->
                </div>
            </div>

        </div>
        
        <div class="lf-modal-janela-rodape -code">
            <a class="lf-botao" href="">Cancelar</a>
            <button type="submit" class="lf-botao -error">Excluir</button>
        </div>

    </div>

</form>


<form 
    id="confirmar-desativacao"
    class="crud-alertas lf-modal lf-tema-light"
    action=""
    >
    <div class="lf-modal-janela -normal" style="width: 450px;">

        <div class="lf-modal-janela-topo -black">
            <b><i class="fa fa-ban"></i> Confirmar Desativação</b>
            <a class="lf-botao -black" href=""><i class="fa fa-times"></i></a>
        </div>	

        <div class="lf-modal-alerta-conteudo" style="font-size: 1.2em;">

            <p>
                Você tem certeza que deseja desativar este(s) registros(s)?
            </p>

            <div class="lf-form" style="margin-top: 0.7em;">

                <div class="lf-form-coluna-label-invertido">
                    <label>Id(s):</label>
                    <input name="dis-id" disabled value="">
                </div>
                
                <div class="inputs-ocultos-para-desativacao lf-none">
                    <!-- preenchido via sld-crud.js com inputs[] a serem desativados. -->
                </div>
            </div>

        </div>
        
        <div class="lf-modal-janela-rodape -code">
            <a class="lf-botao" href="">Cancelar</a>
            <button type="submit" class="lf-botao -error">Desativar</button>
        </div>

    </div>

</form>




<!-- Mensagens ---------------------------------------------------------------->
<div id="desativar-sucesso" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner">
        <div>
            <i class="fa fa-ban crud-alert-icon-alert"></i>
            Registro(s) desativado(s) com sucesso.
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="excluir-sucesso" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner">
        <div>
            <i class="fa fa-times-circle crud-alert-icon-warning"></i>
            Registro(s) excluido(s) com sucesso.
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="criar-sucesso" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner">
        <div>
            <i class="fa fa-check-circle crud-alert-icon-success"></i>
            Registro criado com sucesso.
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="editar-sucesso" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner">
        <div>
            <i class="fa fa-check-circle crud-alert-icon-alert"></i>
            Registro atualizado com sucesso.
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="msg-success" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner" style="max-height: 500px; overflow-x: auto;">
        <div>
            <i class="fa fa-check-circle crud-alert-icon-success"></i>
            <div class="crud-alert-icon-success"><?= $params['msg'] ?? null ?></div>
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="msg-warning" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner" style="max-height: 500px; overflow-x: auto;">
        <div>
            <i class="fa fa-exclamation-circle crud-alert-icon-alert"></i>
            <div class="crud-alert-icon-alert"><?= $params['msg'] ?? null ?></div>
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="msg-info" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner" style="max-height: 500px; overflow-x: auto;">
        <div>
            <i class="fa fa-info-circle crud-alert-icon-info"></i>
            <div class="crud-alert-icon-info"><?= $params['msg'] ?? null ?></div>
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="msg-erro" class="sl-mensagem lt-box -black-o lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner" style="max-height: 500px; overflow-x: auto;">
        <div>
            <i class="fa fa-bug crud-alert-icon-warning"></i>
            <div class="crud-alert-icon-error"><?= $params['msg'] ?? null ?></div>
        </div>
        <a href="" style="color: white;"><i class="fa fa-times"></i></a>        
    </section>
</div>

<div id="msg-alert" class="sl-mensagem lt-box -code lt-shadow alerta-padrao">
    <section class="sl-mensagem-inner" style="max-height: 500px; overflow-x: auto;">
        <div>
            <i class="fa fa-exclamation-circle crud-alert-icon-warning"></i>
            <?= $params['msg'] ?? null ?>
        </div>
        <a href="" style="color: inherit;"><i class="fa fa-times"></i></a>        
    </section>
</div>